version: '3.8'

services:
  vnc_ros:
    build:
      context: ./vnc
    ports:
      - "6080:6080"  # noVNC port
      - "5901:5901"  # VNC port
      - "11311:11311"  # ROS master port
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=vnc_ros
    networks:
      - ros_network

  app_backend:
    build:
      context: ./app
    ports:
      - "8000:8000"  # Web server port
      - "8765:8765"  # WebSocket server port
    environment:
      - ROS_MASTER_URI=http://vnc_ros:11311
      - ROS_HOSTNAME=python_server
    depends_on:
      - vnc_ros
    networks:
      - ros_network

networks:
  ros_network:
    driver: bridge